# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0081552a7261e281e4574be67288ee38bfe463fad315d329148a4b0616076f688d72625dd516bb75ad47745c2c2c2e6caee913eb1e7fc02260b5eed656ec7a49

test:
  secret_key_base: 2bca31750e15fa744f346ba259a48ea4e737faf4927f55d78e193b3982379a24f5b1d7ba9b0609847145dab74c81880b0ad49a4541c587067ef473052cda4bbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
